---
title: "HW4"
author:
  - 熊思源SA24204166
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{hw3}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r}
set.seed(1234)
n <- 1000
m <- 10000
alpha <- 0.1
p_null <- runif(m * n, min = 0, max = 1)
p_alt <- rbeta(m * n, shape1 = 0.1, shape2 = 1)

if (n > m * n) {
  stop("Sample size 'n' is larger than the total number of p-values generated.")
}

p_values <- c(p_null, p_alt)[sample.int(2 * m * n, size = n, replace = FALSE)]
is_null <- sample(c(TRUE, FALSE), size = n, replace = TRUE, prob = c(0.95, 0.05))

p_adj_bonferroni <- pmin(p_values / alpha, 1)
rej_bonferroni <- p_adj_bonferroni <= alpha
fwer_bonferroni <- mean(rej_bonferroni[is_null])
fdr_bonferroni <- mean(rej_bonferroni) - fwer_bonferroni + mean(is_null) * alpha
tpr_bonferroni <- mean(rej_bonferroni[!is_null])

p_adj_bh <- pmin((rank(-p_values, ties.method = "min") - 0.5) / n, 1)
rej_bh <- p_adj_bh <= alpha
fwer_bh <- mean(rej_bh[is_null])
fdr_bh <- mean(rej_bh) - fwer_bh + mean(is_null) * alpha
tpr_bh <- mean(rej_bh[!is_null])

results <- data.frame(
  Bonferroni_correction = c(fwer_bonferroni, fdr_bonferroni, tpr_bonferroni),
  BH_correction = c(fwer_bh, fdr_bh, tpr_bh),
  row.names = c("FWER", "FDR", "TPR")
)
print(results)

```
7.4
```{r}

library(boot)

data <-aircondit

lambda_hat <- sum(data$hours)/length(data$hours)
lambda_hat

```
7.5
```{r}
failure_times <- c(3, 5, 7, 18, 43, 85, 91, 98, 100, 130, 230, 487)

mean_interarrival <- function(data, indices) {
  return(1 / mean(data[indices]))
}

boot_obj <- boot(data = failure_times, statistic = mean_interarrival, R = 1000)

ci_normal <- boot.ci(boot_obj, type = "norm")
ci_basic <- boot.ci(boot_obj, type = "basic")
ci_percentile <- boot.ci(boot_obj, type = "perc")
ci_bca <- boot.ci(boot_obj, type = "bca")

print(ci_normal)
print(ci_basic)
print(ci_percentile)
print(ci_bca)

```

