# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title calculate the value of adjusted Rand Index
#' @import Rcpp
#' @useDynLib SA24204166
#' @param k number of cluster
#' @param n nodes number
#' @param true_label the true label of nodes n x 1 vector
#' @param label the generated label of nodes n x 1 vector
#' @return the value of adjusted Rand Index
#' @export
#' @examples
#' G=DSBM(4,100,0.8,0.4)
#' H=different_model(4,G$cg1,G$cg2,G$g1,G$D,100)
#' ARI(4,100,rep(1:4,each= 25),(H$km1$cluster))
#'
ARI <- function(k, n, true_label, label) {
    .Call('_SA24204166_ARI', PACKAGE = 'SA24204166', k, n, true_label, label)
}

